#!/bin/sh
# run test generated by gcc for m68

#./eagleemu "image load inDebug" "load tests/test.srec" g

./eagleemu "image load bootPrompt.img" "msg all -" "load tests/obj/m68k-elf/test.srec" "bus +" g
